# Generated by Django 6.0.1 on 2026-01-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainprojects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrollimage',
            name='image',
            field=models.ImageField(upload_to='products//'),
        ),
    ]
