# Generated by Django 6.0.1 on 2026-01-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
