# Generated by Django 6.0.1 on 2026-01-12 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiring_for', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('budget', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('personal_note', models.TextField(blank=True)),
                ('hiring_type', models.CharField(choices=[('Freelancing', 'Freelancing'), ('Company', 'Company')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
